plugins:
  - jekyll-relative-links
  - jekyll-toc
relative_links:
  enabled: true
  collections: true
defaults:
  - scope:
      path: ""
    values:
      toc: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - HOWL.md
  - index.md
