plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: minima
toc:
    enabled: true
defaults:
  - scope:
      path: ""
    values:
      toc: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - HOWL.md
  - index.md
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]